version: 0.2

version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     java: corretto11
  # commands:
  #     - npm install -g typescript
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      # - tsc index.ts
      - echo Nothing to do in build phase either xP...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html

